### ISSUE TITLE
utils_1.model.bigNumber(...).computed is not a function

### ISSUE THREAD

**Issue by acandael** [rigby-sh/solace-medusa-starter-api#14]
I cloned the solace-medusa-starter-api and edited the .env file. Configured the database url, the store_cors, admin_cors auth_cors, jwt_secret, cookie_secret, stripe_api_key and stripe_webhook_secret.

When I run 'yarn run dev' in the terminal I get this error:
`utils_1.model.bigNumber(...).computed is not a function`

should I configure anything else to get the server up and running?

Thanks for your help,

Anthony

**Comment by matiasstanghelini** [comment]
Hello, I faced the same error, I did an update of the entire backend to the latest release 2.4.0, following the update process explained in the medusa documentation, is necessary to run the command db:migrate to avoid errors, and this process corrected the error, any questions here I am here to help!

Matias

**Comment by binarycombinatrixcoder** [comment]
panch@/medusa-ecommerce-new/API/solace-medusa-starter-api (main)

$ npx medusa db:migrate
redisUrl not found. A fake redis instance will be used.
info:    Running migrations...
error:   Could not resolve module: Inventory. Error: utils_1.model.bigNumber(...).computed is not a function

error:   utils_1.model.bigNumber(...).computed is not a function
TypeError: utils_1.model.bigNumber(...).computed is not a function
    at Object.<anonymous> (D:\tutorials\showcase\medusa-ecommerce-new\API\solace-medusa-starter-api\node_modules\@medusajs\medusa\node_modules\@medusajs\inventory\src\models\inventory-level.ts:15:43)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Object.require.extensions.<computed> [as .js] (D:\tutorials\showcase\medusa-ecommerce-new\API\solace-medusa-starter-api\node_modules\ts-node\src\index.ts:1608:43)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Function.Module._load (node:internal/modules/cjs/loader:960:12)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (D:\tutorials\showcase\medusa-ecommerce-new\API\solace-medusa-starter-api\node_modules\@medusajs\medusa\node_modules\@medusajs\inventory\src\models\inventory-item.ts:2:1)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)

**Comment by binarycombinatrixcoder** [comment]
@matiasstanghelini 's solution worked out well,

delete node modules folder,
delete lock.json files,

change dependencies and dev dependencies in package.json to -

"dependencies": {
    "@medusajs/admin-sdk": "2.4.0",
    "@medusajs/cli": "2.4.0",
    "@medusajs/framework": "2.4.0",
    "@medusajs/medusa": "2.4.0",
    "@mikro-orm/core": "6.4.3",
    "@mikro-orm/knex": "6.4.3",
    "@mikro-orm/migrations": "6.4.3",
    "@mikro-orm/postgresql": "6.4.3",
    "awilix": "8.0.1",
    "pg": "8.13.0",
    "resend": "^4.0.0"
  },
  "devDependencies": {
    "@medusajs/test-utils": "2.4.0",
    "@mikro-orm/cli": "6.4.3",
    "@swc/core": "1.7.35",
    "@swc/jest": "0.2.36",
    "@types/jest": "29.5.13",
    "@types/node": "22.7.5",
    "@types/react": "18.3.11",
    "@types/react-dom": "18.3.0",
    "jest": "29.7.0",
    "prettier": "^3.3.3",
    "prop-types": "15.8.1",
    "react": "18.3.1",
    "react-dom": "18.3.1",
    "ts-node": "10.9.2",
    "typescript": "5.6.3",
    "vite": "5.4.8"
  },


then run-

npm i
npx medusa db:migrate
npm run dev

that's it!

**Comment by gxy5202** [comment]
> Hello, I faced the same error, I did an update of the entire backend to the latest release `2.4.0`, following the update process explained in the medusa documentation, is necessary to run the command `db:migrate` to avoid errors, and this process corrected the error, any questions here I am here to help!
> 
> Here the update documentation: https://docs.medusajs.com/learn/update#update-medusa-application
> 
> Matias

I did what u suggested, but i got a new issue

![Image](https://github.com/user-attachments/assets/25396002-efeb-45b9-beab-f39595458b33)
